# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-ussuri
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional:
            # We don't run the job on things like neutron docs-only changes
            irrelevant-files: &irrelevant-files
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
              - ^vagrant/.*$
              - ^migration/.*$
              - ^devstack/.*\.sample$
        - neutron-fullstack:
            irrelevant-files: *irrelevant-files
        - neutron-fullstack-with-uwsgi:
            irrelevant-files: *irrelevant-files
        - neutron-grenade-multinode:
            irrelevant-files: *irrelevant-files
        - neutron-grenade-dvr-multinode:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-linuxbridge:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-with-uwsgi:
            irrelevant-files: *irrelevant-files
        - tempest-integrated-networking:
            irrelevant-files: *irrelevant-files
        - tempest-multinode-full-py3:
            voting: false
            irrelevant-files: *irrelevant-files
        - neutron-tempest-dvr-ha-multinode-full:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-iptables_hybrid:
            irrelevant-files: *irrelevant-files
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
            irrelevant-files: *irrelevant-files
        - neutron-tempest-slow-py3:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-ipv6-only:
            irrelevant-files: *irrelevant-files
        - neutron-ovn-tempest-ovs-release:
            irrelevant-files: *irrelevant-files
        - neutron-ovn-tempest-ovs-release-ipv6-only:
            voting: false
            irrelevant-files: *irrelevant-files
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        #    irrelevant-files: *irrelevant-files
        - openstacksdk-functional-devstack-networking:
            voting: false
        - neutron-functional-with-uwsgi:
            voting: false
        - neutron-ovn-tempest-slow:
            voting: false
        - openstack-tox-py36:  # from openstack-python3-ussuri-jobs template
            timeout: 3600
        - openstack-tox-py37:  # from openstack-python3-ussuri-jobs template
            timeout: 3600
        - openstack-tox-py38:  # from openstack-python3-ussuri-jobs template
            timeout: 3600
        - openstack-tox-cover:  # from openstack-cover-jobs template
            timeout: 4800
    gate:
      jobs:
        - neutron-functional
        - neutron-fullstack
        - tempest-integrated-networking
        - neutron-tempest-linuxbridge
        - neutron-tempest-iptables_hybrid
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - openstack-tox-py36:  # from openstack-python3-ussuri-jobs template
            timeout: 3600
        - openstack-tox-py37:  # from openstack-python3-ussuri-jobs template
            timeout: 3600

    experimental:
      jobs:
        - neutron-ovn-grenade

    periodic:
      jobs:
        - neutron-functional
        - neutron-tempest-postgres-full
